// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Category         string
	EventCreators    string
	Events           string
	EventsBookmarks  string
	EventsCategories string
	EventsViews      string
	Ratings          string
	Sessions         string
	Tickets          string
	Users            string
}{
	Category:         "category",
	EventCreators:    "event_creators",
	Events:           "events",
	EventsBookmarks:  "events_bookmarks",
	EventsCategories: "events_categories",
	EventsViews:      "events_views",
	Ratings:          "ratings",
	Sessions:         "sessions",
	Tickets:          "tickets",
	Users:            "users",
}
