// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Category      string
	EventCategory string
	EventCreators string
	Events        string
	EventsViews   string
	Rating        string
	Ticket        string
	Users         string
}{
	Category:      "category",
	EventCategory: "event_category",
	EventCreators: "event_creators",
	Events:        "events",
	EventsViews:   "events_views",
	Rating:        "rating",
	Ticket:        "ticket",
	Users:         "users",
}
