// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EventsBookmark is an object representing the database table.
type EventsBookmark struct {
	ID           int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID       null.Int  `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	EventID      null.Int  `boil:"event_id" json:"event_id,omitempty" toml:"event_id" yaml:"event_id,omitempty"`
	BookmarkDate null.Time `boil:"bookmark_date" json:"bookmark_date,omitempty" toml:"bookmark_date" yaml:"bookmark_date,omitempty"`

	R *eventsBookmarkR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L eventsBookmarkL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EventsBookmarkColumns = struct {
	ID           string
	UserID       string
	EventID      string
	BookmarkDate string
}{
	ID:           "id",
	UserID:       "user_id",
	EventID:      "event_id",
	BookmarkDate: "bookmark_date",
}

var EventsBookmarkTableColumns = struct {
	ID           string
	UserID       string
	EventID      string
	BookmarkDate string
}{
	ID:           "events_bookmarks.id",
	UserID:       "events_bookmarks.user_id",
	EventID:      "events_bookmarks.event_id",
	BookmarkDate: "events_bookmarks.bookmark_date",
}

// Generated where

var EventsBookmarkWhere = struct {
	ID           whereHelperint
	UserID       whereHelpernull_Int
	EventID      whereHelpernull_Int
	BookmarkDate whereHelpernull_Time
}{
	ID:           whereHelperint{field: "\"events_bookmarks\".\"id\""},
	UserID:       whereHelpernull_Int{field: "\"events_bookmarks\".\"user_id\""},
	EventID:      whereHelpernull_Int{field: "\"events_bookmarks\".\"event_id\""},
	BookmarkDate: whereHelpernull_Time{field: "\"events_bookmarks\".\"bookmark_date\""},
}

// EventsBookmarkRels is where relationship names are stored.
var EventsBookmarkRels = struct {
	Event string
	User  string
}{
	Event: "Event",
	User:  "User",
}

// eventsBookmarkR is where relationships are stored.
type eventsBookmarkR struct {
	Event *Event `boil:"Event" json:"Event" toml:"Event" yaml:"Event"`
	User  *User  `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*eventsBookmarkR) NewStruct() *eventsBookmarkR {
	return &eventsBookmarkR{}
}

func (r *eventsBookmarkR) GetEvent() *Event {
	if r == nil {
		return nil
	}
	return r.Event
}

func (r *eventsBookmarkR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// eventsBookmarkL is where Load methods for each relationship are stored.
type eventsBookmarkL struct{}

var (
	eventsBookmarkAllColumns            = []string{"id", "user_id", "event_id", "bookmark_date"}
	eventsBookmarkColumnsWithoutDefault = []string{}
	eventsBookmarkColumnsWithDefault    = []string{"id", "user_id", "event_id", "bookmark_date"}
	eventsBookmarkPrimaryKeyColumns     = []string{"id"}
	eventsBookmarkGeneratedColumns      = []string{}
)

type (
	// EventsBookmarkSlice is an alias for a slice of pointers to EventsBookmark.
	// This should almost always be used instead of []EventsBookmark.
	EventsBookmarkSlice []*EventsBookmark
	// EventsBookmarkHook is the signature for custom EventsBookmark hook methods
	EventsBookmarkHook func(context.Context, boil.ContextExecutor, *EventsBookmark) error

	eventsBookmarkQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	eventsBookmarkType                 = reflect.TypeOf(&EventsBookmark{})
	eventsBookmarkMapping              = queries.MakeStructMapping(eventsBookmarkType)
	eventsBookmarkPrimaryKeyMapping, _ = queries.BindMapping(eventsBookmarkType, eventsBookmarkMapping, eventsBookmarkPrimaryKeyColumns)
	eventsBookmarkInsertCacheMut       sync.RWMutex
	eventsBookmarkInsertCache          = make(map[string]insertCache)
	eventsBookmarkUpdateCacheMut       sync.RWMutex
	eventsBookmarkUpdateCache          = make(map[string]updateCache)
	eventsBookmarkUpsertCacheMut       sync.RWMutex
	eventsBookmarkUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var eventsBookmarkAfterSelectHooks []EventsBookmarkHook

var eventsBookmarkBeforeInsertHooks []EventsBookmarkHook
var eventsBookmarkAfterInsertHooks []EventsBookmarkHook

var eventsBookmarkBeforeUpdateHooks []EventsBookmarkHook
var eventsBookmarkAfterUpdateHooks []EventsBookmarkHook

var eventsBookmarkBeforeDeleteHooks []EventsBookmarkHook
var eventsBookmarkAfterDeleteHooks []EventsBookmarkHook

var eventsBookmarkBeforeUpsertHooks []EventsBookmarkHook
var eventsBookmarkAfterUpsertHooks []EventsBookmarkHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EventsBookmark) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EventsBookmark) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EventsBookmark) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EventsBookmark) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EventsBookmark) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EventsBookmark) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EventsBookmark) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EventsBookmark) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EventsBookmark) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventsBookmarkAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEventsBookmarkHook registers your hook function for all future operations.
func AddEventsBookmarkHook(hookPoint boil.HookPoint, eventsBookmarkHook EventsBookmarkHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		eventsBookmarkAfterSelectHooks = append(eventsBookmarkAfterSelectHooks, eventsBookmarkHook)
	case boil.BeforeInsertHook:
		eventsBookmarkBeforeInsertHooks = append(eventsBookmarkBeforeInsertHooks, eventsBookmarkHook)
	case boil.AfterInsertHook:
		eventsBookmarkAfterInsertHooks = append(eventsBookmarkAfterInsertHooks, eventsBookmarkHook)
	case boil.BeforeUpdateHook:
		eventsBookmarkBeforeUpdateHooks = append(eventsBookmarkBeforeUpdateHooks, eventsBookmarkHook)
	case boil.AfterUpdateHook:
		eventsBookmarkAfterUpdateHooks = append(eventsBookmarkAfterUpdateHooks, eventsBookmarkHook)
	case boil.BeforeDeleteHook:
		eventsBookmarkBeforeDeleteHooks = append(eventsBookmarkBeforeDeleteHooks, eventsBookmarkHook)
	case boil.AfterDeleteHook:
		eventsBookmarkAfterDeleteHooks = append(eventsBookmarkAfterDeleteHooks, eventsBookmarkHook)
	case boil.BeforeUpsertHook:
		eventsBookmarkBeforeUpsertHooks = append(eventsBookmarkBeforeUpsertHooks, eventsBookmarkHook)
	case boil.AfterUpsertHook:
		eventsBookmarkAfterUpsertHooks = append(eventsBookmarkAfterUpsertHooks, eventsBookmarkHook)
	}
}

// One returns a single eventsBookmark record from the query.
func (q eventsBookmarkQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EventsBookmark, error) {
	o := &EventsBookmark{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for events_bookmarks")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EventsBookmark records from the query.
func (q eventsBookmarkQuery) All(ctx context.Context, exec boil.ContextExecutor) (EventsBookmarkSlice, error) {
	var o []*EventsBookmark

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EventsBookmark slice")
	}

	if len(eventsBookmarkAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EventsBookmark records in the query.
func (q eventsBookmarkQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count events_bookmarks rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q eventsBookmarkQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if events_bookmarks exists")
	}

	return count > 0, nil
}

// Event pointed to by the foreign key.
func (o *EventsBookmark) Event(mods ...qm.QueryMod) eventQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.EventID),
	}

	queryMods = append(queryMods, mods...)

	return Events(queryMods...)
}

// User pointed to by the foreign key.
func (o *EventsBookmark) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadEvent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (eventsBookmarkL) LoadEvent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEventsBookmark interface{}, mods queries.Applicator) error {
	var slice []*EventsBookmark
	var object *EventsBookmark

	if singular {
		var ok bool
		object, ok = maybeEventsBookmark.(*EventsBookmark)
		if !ok {
			object = new(EventsBookmark)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEventsBookmark)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEventsBookmark))
			}
		}
	} else {
		s, ok := maybeEventsBookmark.(*[]*EventsBookmark)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEventsBookmark)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEventsBookmark))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &eventsBookmarkR{}
		}
		if !queries.IsNil(object.EventID) {
			args = append(args, object.EventID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventsBookmarkR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.EventID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.EventID) {
				args = append(args, obj.EventID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`events`),
		qm.WhereIn(`events.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Event")
	}

	var resultSlice []*Event
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Event")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for events")
	}

	if len(eventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Event = foreign
		if foreign.R == nil {
			foreign.R = &eventR{}
		}
		foreign.R.EventsBookmarks = append(foreign.R.EventsBookmarks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.EventID, foreign.ID) {
				local.R.Event = foreign
				if foreign.R == nil {
					foreign.R = &eventR{}
				}
				foreign.R.EventsBookmarks = append(foreign.R.EventsBookmarks, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (eventsBookmarkL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEventsBookmark interface{}, mods queries.Applicator) error {
	var slice []*EventsBookmark
	var object *EventsBookmark

	if singular {
		var ok bool
		object, ok = maybeEventsBookmark.(*EventsBookmark)
		if !ok {
			object = new(EventsBookmark)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEventsBookmark)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEventsBookmark))
			}
		}
	} else {
		s, ok := maybeEventsBookmark.(*[]*EventsBookmark)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEventsBookmark)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEventsBookmark))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &eventsBookmarkR{}
		}
		if !queries.IsNil(object.UserID) {
			args = append(args, object.UserID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventsBookmarkR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.UserID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.UserID) {
				args = append(args, obj.UserID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.EventsBookmarks = append(foreign.R.EventsBookmarks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.EventsBookmarks = append(foreign.R.EventsBookmarks, local)
				break
			}
		}
	}

	return nil
}

// SetEvent of the eventsBookmark to the related item.
// Sets o.R.Event to related.
// Adds o to related.R.EventsBookmarks.
func (o *EventsBookmark) SetEvent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Event) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"events_bookmarks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"event_id"}),
		strmangle.WhereClause("\"", "\"", 2, eventsBookmarkPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.EventID, related.ID)
	if o.R == nil {
		o.R = &eventsBookmarkR{
			Event: related,
		}
	} else {
		o.R.Event = related
	}

	if related.R == nil {
		related.R = &eventR{
			EventsBookmarks: EventsBookmarkSlice{o},
		}
	} else {
		related.R.EventsBookmarks = append(related.R.EventsBookmarks, o)
	}

	return nil
}

// RemoveEvent relationship.
// Sets o.R.Event to nil.
// Removes o from all passed in related items' relationships struct.
func (o *EventsBookmark) RemoveEvent(ctx context.Context, exec boil.ContextExecutor, related *Event) error {
	var err error

	queries.SetScanner(&o.EventID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("event_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Event = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.EventsBookmarks {
		if queries.Equal(o.EventID, ri.EventID) {
			continue
		}

		ln := len(related.R.EventsBookmarks)
		if ln > 1 && i < ln-1 {
			related.R.EventsBookmarks[i] = related.R.EventsBookmarks[ln-1]
		}
		related.R.EventsBookmarks = related.R.EventsBookmarks[:ln-1]
		break
	}
	return nil
}

// SetUser of the eventsBookmark to the related item.
// Sets o.R.User to related.
// Adds o to related.R.EventsBookmarks.
func (o *EventsBookmark) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"events_bookmarks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, eventsBookmarkPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &eventsBookmarkR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			EventsBookmarks: EventsBookmarkSlice{o},
		}
	} else {
		related.R.EventsBookmarks = append(related.R.EventsBookmarks, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct.
func (o *EventsBookmark) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.EventsBookmarks {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.EventsBookmarks)
		if ln > 1 && i < ln-1 {
			related.R.EventsBookmarks[i] = related.R.EventsBookmarks[ln-1]
		}
		related.R.EventsBookmarks = related.R.EventsBookmarks[:ln-1]
		break
	}
	return nil
}

// EventsBookmarks retrieves all the records using an executor.
func EventsBookmarks(mods ...qm.QueryMod) eventsBookmarkQuery {
	mods = append(mods, qm.From("\"events_bookmarks\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"events_bookmarks\".*"})
	}

	return eventsBookmarkQuery{q}
}

// FindEventsBookmark retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEventsBookmark(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*EventsBookmark, error) {
	eventsBookmarkObj := &EventsBookmark{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"events_bookmarks\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, eventsBookmarkObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from events_bookmarks")
	}

	if err = eventsBookmarkObj.doAfterSelectHooks(ctx, exec); err != nil {
		return eventsBookmarkObj, err
	}

	return eventsBookmarkObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EventsBookmark) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no events_bookmarks provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventsBookmarkColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	eventsBookmarkInsertCacheMut.RLock()
	cache, cached := eventsBookmarkInsertCache[key]
	eventsBookmarkInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			eventsBookmarkAllColumns,
			eventsBookmarkColumnsWithDefault,
			eventsBookmarkColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(eventsBookmarkType, eventsBookmarkMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(eventsBookmarkType, eventsBookmarkMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"events_bookmarks\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"events_bookmarks\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into events_bookmarks")
	}

	if !cached {
		eventsBookmarkInsertCacheMut.Lock()
		eventsBookmarkInsertCache[key] = cache
		eventsBookmarkInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EventsBookmark.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EventsBookmark) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	eventsBookmarkUpdateCacheMut.RLock()
	cache, cached := eventsBookmarkUpdateCache[key]
	eventsBookmarkUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			eventsBookmarkAllColumns,
			eventsBookmarkPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update events_bookmarks, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"events_bookmarks\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, eventsBookmarkPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(eventsBookmarkType, eventsBookmarkMapping, append(wl, eventsBookmarkPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update events_bookmarks row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for events_bookmarks")
	}

	if !cached {
		eventsBookmarkUpdateCacheMut.Lock()
		eventsBookmarkUpdateCache[key] = cache
		eventsBookmarkUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q eventsBookmarkQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for events_bookmarks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for events_bookmarks")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EventsBookmarkSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventsBookmarkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"events_bookmarks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, eventsBookmarkPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in eventsBookmark slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all eventsBookmark")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EventsBookmark) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no events_bookmarks provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventsBookmarkColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	eventsBookmarkUpsertCacheMut.RLock()
	cache, cached := eventsBookmarkUpsertCache[key]
	eventsBookmarkUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			eventsBookmarkAllColumns,
			eventsBookmarkColumnsWithDefault,
			eventsBookmarkColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			eventsBookmarkAllColumns,
			eventsBookmarkPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert events_bookmarks, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(eventsBookmarkPrimaryKeyColumns))
			copy(conflict, eventsBookmarkPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"events_bookmarks\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(eventsBookmarkType, eventsBookmarkMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(eventsBookmarkType, eventsBookmarkMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert events_bookmarks")
	}

	if !cached {
		eventsBookmarkUpsertCacheMut.Lock()
		eventsBookmarkUpsertCache[key] = cache
		eventsBookmarkUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EventsBookmark record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EventsBookmark) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EventsBookmark provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), eventsBookmarkPrimaryKeyMapping)
	sql := "DELETE FROM \"events_bookmarks\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from events_bookmarks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for events_bookmarks")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q eventsBookmarkQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no eventsBookmarkQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from events_bookmarks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for events_bookmarks")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EventsBookmarkSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(eventsBookmarkBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventsBookmarkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"events_bookmarks\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventsBookmarkPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from eventsBookmark slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for events_bookmarks")
	}

	if len(eventsBookmarkAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EventsBookmark) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEventsBookmark(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EventsBookmarkSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EventsBookmarkSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventsBookmarkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"events_bookmarks\".* FROM \"events_bookmarks\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventsBookmarkPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EventsBookmarkSlice")
	}

	*o = slice

	return nil
}

// EventsBookmarkExists checks if the EventsBookmark row exists.
func EventsBookmarkExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"events_bookmarks\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if events_bookmarks exists")
	}

	return exists, nil
}

// Exists checks if the EventsBookmark row exists.
func (o *EventsBookmark) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EventsBookmarkExists(ctx, exec, o.ID)
}
